- name: Update apt cache for Ubuntu
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Nginx on Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_facts['os_family'] == "Debian"
  notify: restart nginx


- name: Install EPEL package and Nginx on CentOS =v.7= 
  raw: sudo yum install -y epel-release nginx
  when: ansible_facts['os_family'] == "RedHat"
  notify: restart nginx


- name: Nginx service status check
  service:
    name: nginx
    state: started
    enabled: yes