chatApp:
  name: nginx
  image: "nginx:1.14.2"
  replicaCount: 3
  containerPort: 80
  labels:
    app: nginx
    env: prod

redis:
  name: redis
  image: "redis:7.2-alpine"
  replicaCount: 1
  containerPort: 6379
  storage:
    size: 1Gi
    mountPath: "/data"
  labels:
    app: redis

serviceAccount:
  create: true
  name: ""

