apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
spec:
  serviceName: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.labels.app }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.redis.storage.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}