apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.redis.labels.app }}
  ports:
    - port: {{ .Values.redis.containerPort }}