apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  hostNetwork: true
  nodeName: node1
  nodeIP: 10.0.0.5
